/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataStoreTypes } from './dataStoreTypes';
import { DataStoreSubTypes } from './dataStoreSubTypes';


/**
 * Data store
 */
export interface DataStore { 
    /**
     * Workspce in which the data store is present.
     */
    workspace: string;
    /**
     * The user who created the data store.
     */
    user_name: string;
    /**
     * Name of the data store.
     */
    name: string;
    type: DataStoreTypes;
    sub_type?: DataStoreSubTypes;
    /**
     * Name of the Vector DB profile.
     */
    vectordb_profile?: string;
    /**
     * The embedding model to be used while ingesting data (applies for vector DB only)
     */
    vectordb_embedding?: string;
    /**
     * The endpoint of the structure database such as SQL/MongoDB.
     */
    structdb_url?: string;
    /**
     * The name of the database in the structured database.
     */
    structdb_name?: string;
    /**
     * The name of the table in the structured database.
     */
    structdb_table?: string;
}
export namespace DataStore {
}


