/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InputFilter } from './inputFilter';
import { InputKeys } from './inputKeys';
import { IngestParams } from './ingestParams';
import { IngestTypes } from './ingestTypes';
import { InputTypes } from './inputTypes';


/**
 * Data store ingest parameters
 */
export interface DataStoreIngest { 
    /**
     * The workspace this data store belongs to.
     */
    workspace: string;
    /**
     * Name of the data store
     */
    data_store_name: string;
    input_filter: InputFilter;
    input_keys?: InputKeys;
    input_type: InputTypes;
    ingest_type: IngestTypes;
    ingest_params?: IngestParams;
}
export namespace DataStoreIngest {
}


