/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataStoreInfo } from './dataStoreInfo';


/**
 * This contains an configuration and operational information for an array of data stores and is returned for GET operations.
 */
export interface DataStores { 
    data_stores?: Array<DataStoreInfo>;
}

