/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QueryTypes } from './queryTypes';
import { QueryParams } from './queryParams';


/**
 * Data Store Query
 */
export interface DataStoreQuery { 
    /**
     * The workspace this data store is created in.
     */
    workspace: string;
    /**
     * Name of the data store.
     */
    data_store_name: string;
    /**
     * The embedding model to be used.
     */
    embedding_model: string;
    /**
     * The LLM model to be used.
     */
    llm_model: string;
    query_params?: QueryParams;
    /**
     * The actual query string for which the user wants a response to.
     */
    query_string: string;
    query_type: QueryTypes;
}
export namespace DataStoreQuery {
}


