/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The different sub-types of data stores that are supported. Sub-type validity will be determined by the data store type.
 */
export type DataStoreSubTypes = 1 | 2;

export const DataStoreSubTypes = {
    DBTYPE_SQL: 1 as DataStoreSubTypes,
    DBTYPE_MONGO: 2 as DataStoreSubTypes
};

