/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataStoreTypes } from './dataStoreTypes';
import { VectordbStore } from './vectordbStore';
import { StructdbStore } from './structdbStore';


/**
 * This is the data store specification that is used for creating and updating a data store. Data stores can be of different types including a vector database. Some parameters are mandatory based on the type of database chosen and it will be indicated along with the parameter.
 */
export interface DataStore { 
    /**
     * Workspace in which the data store is present.
     */
    workspace: string;
    /**
     * Name of the data store.
     */
    name: string;
    store_type: DataStoreTypes;
    vectordb_store?: VectordbStore;
    structdb_store?: StructdbStore;
}
export namespace DataStore {
}


