/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DataStoreTypes = 1 | 2 | 3;

export const DataStoreTypes = {
    DataStoreType_Vector: 1 as DataStoreTypes,
    DataStoreType_Structured: 2 as DataStoreTypes,
    DataStoreType_Image: 3 as DataStoreTypes
};

