/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The different types of data stores that are supported.
 */
export type DataStoreTypes = 1 | 2 | 3;

export const DataStoreTypes = {
    VECTOR_DATABASE: 1 as DataStoreTypes,
    STRUCTURED_DATABASE: 2 as DataStoreTypes,
    IMAGE_DATABASE: 3 as DataStoreTypes
};

