/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DataStoreSubTypes = 1 | 2;

export const DataStoreSubTypes = {
    DataStoreSubType_SQL: 1 as DataStoreSubTypes,
    DataStoreType_MongoDB: 2 as DataStoreSubTypes
};

