/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataStoreTypes } from './dataStoreTypes';
import { VectordbStore } from './vectordbStore';
import { StructdbStore } from './structdbStore';


/**
 * This contains configuration and operational information about a single data store and is returned for GET operation.
 */
export interface DataStoreInfo { 
    /**
     * Workspace in which the data store is present.
     */
    workspace: string;
    /**
     * Name of the data store.
     */
    name: string;
    /**
     * The user who created the data store.
     */
    user_name: string;
    store_type: DataStoreTypes;
    vectordb_store?: VectordbStore;
    structdb_store?: StructdbStore;
    /**
     * Timestamp of the data store creation.
     */
    created_at: number;
    /**
     * Timestamp of the last update to the data store.
     */
    last_update: number;
    /**
     * Timestamp of last query using the data store.
     */
    last_query: number;
    /**
     * Timestamp of the last ingestion to the data store.
     */
    last_ingest: number;
    /**
     * Number of direct ingestions done to the data store until now.
     */
    direct_ingest_count: number;
    /**
     * Number of pipeline ingestions done to the data store until now.
     */
    pipeline_ingest_count: number;
    /**
     * Number of ingestions resulting in errors.
     */
    error_ingest_count: number;
}
export namespace DataStoreInfo {
}


