/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Provides additional information about delete operation results.
 */
export interface DeleteResponse { 
    /**
     * The total number of deleted records.
     */
    deleted_records?: number;
    /**
     * Any message that is returned as a result of the operation.
     */
    response?: string;
}

