/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The type of file extractors available.
 */
export type FileExtractors = 1 | 2;

export const FileExtractors = {
    EXTRACTOR_PYMUPDF: 1 as FileExtractors,
    EXTRACTOR_LLAMAPARSE: 2 as FileExtractors
};

