/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The type of ingestion required
 */
export type IngestTypes = 1 | 2 | 3;

export const IngestTypes = {
    INGEST_TEXT: 1 as IngestTypes,
    INGEST_IMAGE: 2 as IngestTypes,
    INGEST_CUSTOM: 3 as IngestTypes
};

