/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IngestPipelineInfo } from './ingestPipelineInfo';


export interface IngestPipelines { 
    ingest_pipelines?: Array<IngestPipelineInfo>;
}

