/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Run an ingest pipeline immediately.
 */
export interface IngestPipelineRun { 
    /**
     * The workspace this ingest pipeline belongs to.
     */
    workspace: string;
    /**
     * Name of the ingest pipeline.
     */
    name: string;
    /**
     * The name of the parent data store in which this ingest pipeline is present.
     */
    data_store_name: string;
}

