/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IngestPipelineRunStatus { 
    /**
     * Status of the operation, true indicates success.
     */
    status?: boolean;
    /**
     * Any associated error message in case the status is false.
     */
    error?: string;
}

