/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The type of ingestion required
 */
export type IngestTypes = 1 | 2 | 3;

export const IngestTypes = {
    IngestType_Text: 1 as IngestTypes,
    IngestType_Images: 2 as IngestTypes,
    IngestType_Custom: 3 as IngestTypes
};

