/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InputFilter } from './inputFilter';
import { InputKeys } from './inputKeys';
import { IngestParams } from './ingestParams';
import { IngestTypes } from './ingestTypes';
import { InputTypes } from './inputTypes';


/**
 * Ingest Pipeline configuration and operation information.
 */
export interface IngestPipelineInfo { 
    /**
     * Workspce in which the data store is present.
     */
    workspace: string;
    /**
     * The user who created the ingest pipeline.
     */
    user_name: string;
    /**
     * Name of the ingest pipeline.
     */
    name: string;
    /**
     * The name of the parent data store in which this ingest pipeline is present.
     */
    data_store_name: string;
    input_filter: InputFilter;
    input_keys?: InputKeys;
    input_type: InputTypes;
    ingest_type: IngestTypes;
    ingest_params?: IngestParams;
    timer_on?: boolean;
    timer_interval?: number;
    /**
     * Timestamp of the ingest pipeline creation.
     */
    created_at: number;
    /**
     * Timestamp of the last update to the ingest pipeline.
     */
    last_update: number;
}
export namespace IngestPipelineInfo {
}


