/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IngestPipelineInfo } from './ingestPipelineInfo';


/**
 * A list of individual ingest pipeline configuration and operation information that is returned in GET requests.
 */
export interface IngestPipelines { 
    /**
     * A list of individual ingest pipeline configuration and operation information that is returned in GET requests.
     */
    ingest_pipelines?: Array<IngestPipelineInfo>;
}

