/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The location of the input file(s)
 */
export type InputTypes = 1 | 2 | 3 | 4;

export const InputTypes = {
    InputType_AWSS3: 1 as InputTypes,
    InputType_AzureBlob: 2 as InputTypes,
    InputType_Webpage: 3 as InputTypes,
    InputType_Local: 4 as InputTypes
};

