/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Security keys required to access the input files. Not recommended in production
 */
export interface InputKeys { 
    /**
     * Azure Client ID.
     */
    az_client_id?: string;
    /**
     * Azure Client Secret.
     */
    az_client_secret?: string;
    /**
     * Azure Tenant ID.
     */
    az_tenant_id?: string;
    /**
     * AWS Access Key
     */
    aws_access_key?: string;
    /**
     * AWS Secret Token
     */
    aws_secret_token?: string;
}

