/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The parameters used to filter file(s) for ingestion
 */
export interface InputFilter { 
    /**
     * Comma separated list of file(s) to be picked for ingestion. Supports wildcards
     */
    files_list?: string;
    /**
     * Name of the blob incase of Azure storage.
     */
    az_blob?: string;
    /**
     * Name of the account URL incase of Azure storage.
     */
    az_account_url?: string;
    /**
     * Name of the S3 bucket in case of AWS storage.
     */
    s3_bucket?: string;
}

