/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The location of the input file(s)
 */
export type InputTypes = 1 | 2 | 3 | 4;

export const InputTypes = {
    SOURCE_AWS_S3: 1 as InputTypes,
    SOURCE_AZURE_BLOB: 2 as InputTypes,
    SOURCE_WEBPAGE: 3 as InputTypes,
    SOURCE_LOCAL: 4 as InputTypes
};

