/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LogLevels } from './logLevels';


/**
 * The various logs that are generated filtered based on user, workspace and timeframes.
 */
export interface LogInfo { 
    /**
     * Workspce in which the log was genereated.
     */
    workspace: string;
    /**
     * The user for which this log was generated.
     */
    user_name: string;
    level: LogLevels;
    /**
     * The topic of the log message.
     */
    topic: string;
    /**
     * The timestamp of the generated log message.
     */
    timestamp: number;
    /**
     * The log message generated for the user.
     */
    message: string;
}
export namespace LogInfo {
}


