/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type LogLevels = 1 | 2 | 3 | 4;

export const LogLevels = {
    LogLevel_Debug: 1 as LogLevels,
    LogLevel_Info: 2 as LogLevels,
    LogLevel_Warn: 3 as LogLevels,
    LogLevel_Error: 4 as LogLevels
};

