/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type LogLevel = 1 | 2 | 3 | 4;

export const LogLevel = {
    Debug: 1 as LogLevel,
    Info: 2 as LogLevel,
    Warn: 3 as LogLevel,
    Error: 4 as LogLevel
};

