/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type LogLevels = 1 | 2 | 3 | 4;

export const LogLevels = {
    LOG_LEVEL_DEBUG: 1 as LogLevels,
    LOG_LEVEL_INFO: 2 as LogLevels,
    LOG_LEVEL_WARN: 3 as LogLevels,
    LOG_LEVEL_ERROR: 4 as LogLevels
};

