/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelProviders } from './modelProviders';
import { ModelEndpoints } from './modelEndpoints';


/**
 * model profile
 */
export interface ModelProfile { 
    /**
     * Name of the model profile.
     */
    name: string;
    provider: ModelProviders;
    endpoint?: ModelEndpoints;
    /**
     * List of models allowed for a user who is associated to this profile. Incase list is empty all models available in the provider are allowed.
     */
    allowed_models?: Array<string>;
    /**
     * Access Key for accessing the model. It is possible to specify the access key as a secret value using either of the following formats {Azure:KeyVault-Name:Key} or {AWS:SecretName:Key} or {AWS:Region:SecretName:Key}.
     */
    access_key: string;
}
export namespace ModelProfile {
}


