/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelProviders } from './modelProviders';


/**
 * model profile
 */
export interface ModelProfile { 
    /**
     * Name of the model profile.
     */
    name: string;
    model_provider: ModelProviders;
    /**
     * List of models allowed for a user who is associated to this profile. Incase list is empty all models available in the provider are allowed.
     */
    allowed_models?: Array<string>;
    /**
     * Access Key for accessing the model.
     */
    access_key: string;
}
export namespace ModelProfile {
}


