/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The list of model providers supported
 */
export type ModelProviders = 1 | 2;

export const ModelProviders = {
    Provider_OpenAI: 1 as ModelProviders,
    Provider_Gemini: 2 as ModelProviders
};

