/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelProviders } from './modelProviders';
import { ModelEndpoints } from './modelEndpoints';


/**
 * Model profile Information
 */
export interface ModelProfileInfo { 
    /**
     * Name of the model profile.
     */
    name: string;
    provider?: ModelProviders;
    /**
     * List of models allowed for a user who is associated to this profile. Incase list is empty all models available in the provider are allowed.
     */
    allowed_models?: Array<string>;
    endpoint?: ModelEndpoints;
    /**
     * Access Key for accessing the model
     */
    access_key: string;
    /**
     * The username who created this model profile
     */
    created_by: string;
    /**
     * Timestamp of the model profile creation
     */
    created_at: number;
    /**
     * Timestamp of the last update to the model profile
     */
    last_update: number;
}
export namespace ModelProfileInfo {
}


