/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelProfileInfo } from './modelProfileInfo';


export interface ModelProfiles { 
    model_profiles?: Array<ModelProfileInfo>;
}

