/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Model profile Information
 */
export interface ModelEndpoints { 
    /**
     * The AWS region in case of AWS Bedrock Provider.
     */
    aws_region?: string;
}

