/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The list of model providers supported
 */
export type ModelProviders = 1 | 2 | 3;

export const ModelProviders = {
    OPENAI: 1 as ModelProviders,
    GEMINI: 2 as ModelProviders,
    AWS_BEDROCK: 3 as ModelProviders
};

