/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MonitorProfileInfo } from './monitorProfileInfo';


export interface MonitorProfiles { 
    monitor_profiles?: Array<MonitorProfileInfo>;
}

