/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MonitorProviders } from './monitorProviders';


/**
 * This describes the details of a particular monitor profile.
 */
export interface MonitorProfile { 
    /**
     * Name of the monitor profile.
     */
    name: string;
    provider: MonitorProviders;
    /**
     * Access Key for accessing the monitoring tool.
     */
    access_key: string;
    /**
     * URL of the monitoring tool endpoint.
     */
    endpoint: string;
}
export namespace MonitorProfile {
}


