/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MonitorProviders } from './monitorProviders';


/**
 * This describes the details of a particular monitor profile.
 */
export interface MonitorProfileInfo { 
    /**
     * Name of the monitor profile.
     */
    name: string;
    provider: MonitorProviders;
    /**
     * URL of the monitoring tool endpoint.
     */
    endpoint: string;
    /**
     * Access Key for accessing the monitoring tool.
     */
    access_key?: string;
    /**
     * Identifies the user who created this monitor profile.
     */
    created_by: string;
    /**
     * Timestamp of the monitor profile creation.
     */
    created_at: number;
    /**
     * Timestamp of the last update to the monitor profile.
     */
    last_update: number;
}
export namespace MonitorProfileInfo {
}


