/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The list of monitoring providers
 */
export type MonitorProviders = 1;

export const MonitorProviders = {
    LANGFUSE: 1 as MonitorProviders
};

