/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Query response
 */
export interface QueryResponse { 
    /**
     * Response from LLM for the user query.
     */
    response?: string;
}

