/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The type of query.
 */
export type QueryTypes = 1 | 2 | 3 | 4;

export const QueryTypes = {
    QueryType_Text: 1 as QueryTypes,
    QueryType_TextAndImage: 2 as QueryTypes,
    QueryType_SQL: 3 as QueryTypes,
    QueryType_ChainOfThought: 4 as QueryTypes
};

