/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Defines the handling of scenarios where the context cannot fit the entire query with vector retrievals.
 */
export type QueryTypes = 1 | 2;

export const QueryTypes = {
    TEXT_QUERY: 1 as QueryTypes,
    SQL_QUERY: 2 as QueryTypes
};

