/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A data store query request
 */
export interface QueryParams { 
    /**
     * The number of vector db matches to consider for llm context
     */
    top_k?: number;
    /**
     * The temperature of the LLM processing, the higher the more creative the LLM is.
     */
    model_temperature?: number;
    query_mode?: string;
}

