/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The mode of LLM query.
 */
export type QueryModes = 1 | 2 | 3;

export const QueryModes = {
    QueryMode_Refine: 1 as QueryModes,
    QueryMode_Compact: 2 as QueryModes,
    QueryMode_Accumulate: 3 as QueryModes
};

