/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QueryPipelineInfo } from './queryPipelineInfo';


export interface QueryPipelines { 
    query_pipelines?: Array<QueryPipelineInfo>;
}

