/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QueryModes } from './queryModes';


/**
 * A data store query request
 */
export interface QueryParams { 
    /**
     * The number of vector db matches to consider for llm context
     */
    top_k?: number;
    /**
     * The temperature of the LLM processing, the higher the more creative the LLM is.
     */
    temperature?: number;
    /**
     * Dictionary of metadata key/value pairs that are to be inserted into the vector database along with the chunks. This is useful while retrieval to restrict the relevant chunks.
     */
    doc_metadata?: { [key: string]: string; };
    query_mode?: QueryModes;
}
export namespace QueryParams {
}


