/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataStoreSubTypes } from './dataStoreSubTypes';


/**
 * This is the data store specification structured databases.
 */
export interface StructdbStore { 
    sub_type: DataStoreSubTypes;
    /**
     * The endpoint of the structure database such as SQL/MongoDB. This string can contain keystore specification for any sensitive information. This is a mandatory parameter for structured and image databases.
     */
    connect_string: string;
    /**
     * The name of the database in the structured database This is a mandatory parameter for structured and image databases.
     */
    database_name: string;
    /**
     * The name of the table in the structured database. This is a mandatory parameter for structured and image databases.
     */
    table_name: string;
}
export namespace StructdbStore {
}


