/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TokenStatsInfo } from './tokenStatsInfo';


export interface TokenStats { 
    token_stats?: Array<TokenStatsInfo>;
}

