/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The various logs that are generated filtered based on user, workspace and timeframes.
 */
export interface TokenStatsInfo { 
    /**
     * Workspce in which the log was genereated.
     */
    workspace: string;
    /**
     * The user for which this log was generated.
     */
    user_name: string;
    /**
     * The embedding model used in the operation.
     */
    embed_model?: string;
    /**
     * The total number of tokens used for generating the embedding.
     */
    embed_tokens?: number;
    /**
     * The LLM model used in the operation.
     */
    llm_model?: string;
    /**
     * The total number of tokens used for the prompt.
     */
    prompt_tokens?: number;
    /**
     * The total number of tokens used for the query completion.
     */
    completion_tokens?: number;
    /**
     * The total files consumed incase of an ingest operation.
     */
    total_files?: number;
    /**
     * The total size of content consumed incase of an ingest operation.
     */
    total_size?: number;
    /**
     * The time taken to perform the underlying RAG operation.
     */
    latency?: number;
    /**
     * The timestamp of the generated log message.
     */
    timestamp: number;
}

