/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserProfileInfo } from './userProfileInfo';


export interface UserProfiles { 
    user_profiles?: Array<UserProfileInfo>;
}

