/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * This is the data store specification vector databases.
 */
export interface VectordbStore { 
    /**
     * Name of the Vector DB profile. This is mandatory parameter in case of vector database.
     */
    vectordb_profile: string;
    /**
     * The embedding model to be used while ingesting data. This is mandatory parameter in case of vector database.
     */
    embedding_model: string;
    /**
     * This describes whether the data store is shared with others in the account for query purposes.
     */
    shared?: boolean;
}

