/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VectorStoreInfo } from './vectorStoreInfo';


/**
 * This contains an configuration and operational information for an array of vector stores and is returned for GET operations.
 */
export interface VectorStores { 
    vector_stores?: Array<VectorStoreInfo>;
}

