/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VectorStoreStatusTypes } from './vectorStoreStatusTypes';


/**
 * This contains information specific to the vector database obtained from the provider.
 */
export interface VectorStoreInfo { 
    /**
     * Workspace in which the data store is present.
     */
    workspace: string;
    /**
     * Name of the data store.
     */
    data_store_name: string;
    status: VectorStoreStatusTypes;
    /**
     * Dimensions in case of a vector database.
     */
    dimension?: number;
    /**
     * Total number of document chunks in case of a vector database.
     */
    total_records?: number;
    /**
     * The list of files present in the vector database.
     */
    files?: Array<string>;
}
export namespace VectorStoreInfo {
}


