/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The different status denominators for the vector store in the provider.
 */
export type VectorStoreStatusTypes = 1 | 2 | 3;

export const VectorStoreStatusTypes = {
    STATUS_ACTIVE: 1 as VectorStoreStatusTypes,
    STATUS_NOTPRESENT: 2 as VectorStoreStatusTypes,
    STATUS_INCOMPLETE: 3 as VectorStoreStatusTypes
};

