/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VectordbProfileInfo } from './vectordbProfileInfo';


export interface VectordbProfiles { 
    vectordb_profiles?: Array<VectordbProfileInfo>;
}

