/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The parameters used to connect the vector database.
 */
export interface VectordbEndpoint { 
    /**
     * Connection string used to connect to the database, this can include password in case of some providers.
     */
    connect_string?: string;
    /**
     * Name of the database to which the profile connects.
     */
    database?: string;
    /**
     * The specific collection within the database where data will be stored.
     */
    collection?: string;
    /**
     * Indicates the cloud provider, e.g., AWS, Azure.
     */
    cloud?: string;
    /**
     * Specifies the cloud region (e.g., us-west-2) where the database or collection is hosted.
     */
    region?: string;
}

