/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The list of vector database providers supported
 */
export type VectordbProviders = 1 | 2 | 3;

export const VectordbProviders = {
    Vectordb_Pinecone: 1 as VectordbProviders,
    Vectordb_Internal: 2 as VectordbProviders,
    Vectordb_Mongodb: 3 as VectordbProviders
};

