/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkspaceInfo } from './workspaceInfo';


export interface Workspaces { 
    workspaces?: Array<WorkspaceInfo>;
}

