/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Worker configuration and operation information.
 */
export interface WorkerInfo { 
    /**
     * Name of the worker.
     */
    name: string;
    /**
     * The unique identifier that is automatically assigned to the worker.
     */
    worker_id: string;
    /**
     * The client secret that is used to authenticate the worker. This needs to be provided when a worker tries to join Majordomo director.
     */
    access_key: string;
    /**
     * Indicates whether the worker is currently connected to the director.
     */
    client_status: boolean;
    /**
     * Timestamp of the worker creation.
     */
    created_at: number;
    /**
     * Timestamp of the last update to the worker.
     */
    last_update: number;
}

