/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The worker node that is used to connect the user network to the director.
 */
export interface Worker { 
    /**
     * Name of the worker.
     */
    name: string;
}

