/**
 * Majordomo AI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WorkerInfo } from './workerInfo';


export interface Workers { 
    workers?: Array<WorkerInfo>;
}

